services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=suchef
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8434:5432"

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - .:/tyuiu_bot
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tyuiu_bot
    depends_on:
      - postgres


volumes:
  postgres_data:
