services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=suchef
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8434:5432"

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - .:/tyuiu_bot
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tyuiu_bot
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - bot_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - bot_network


volumes:
  postgres_data:


networks:
  bot_network:
    driver: bridge