""" revision

Revision ID: 7f83aa73b3d4
Revises: 7782ba4436c8
Create Date: 2025-05-01 20:50:49.905709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f83aa73b3d4'
down_revision: Union[str, None] = '7782ba4436c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.create_table('contacts',
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], name='contacts_telegram_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey'),
    sa.UniqueConstraint('telegram_id', name='contacts_telegram_id_key')
    )
    # ### end Alembic commands ###
