name: Tyuiu-RAG-Bot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest


    env:
        ALL: >
           BOT_TOKEN = ${{ secrets.BOT_TOKEN }}
           DB_USER = ${{ secrets.DB_USER }}
           DB_PASSWORD = ${{ secrets.DB_PASSWORD }}
           DB_HOST = ${{ secrets.DB_HOST }}
           DB_PORT = ${{ secrets.DB_PORT }}
           DB_NAME = ${{ secrets.DB_NAME }}
           CHAT_API_BASE_URL = ${{ secrets.CHAT_API_BASE_URL }}
           APP_BASE_URL = ${{ secrets.APP_BASE_URL }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Create .env file
          run: |
            echo "$ALL" >> .env
        
        - name: Set environment variables
          run: |
             echo "BACKEND_IMAGE=$(echo ${{env.BACKEND_IMAGE}} )" >> $GITHUB_ENV
            
        - name: Build images
          run: |
            docker compose -f 'docker-compose.yml' up -d --build